# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-22 22:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('title', models.CharField(blank=True, default='', max_length=128)),
                ('caption', models.CharField(blank=True, default='', max_length=128)),
                ('alt_text', models.CharField(blank=True, default='', max_length=128)),
                ('slug', models.SlugField(blank=True, default='', max_length=64)),
                ('extension', models.CharField(blank=True, default='', max_length=16)),
                ('height', models.IntegerField(default=0)),
                ('width', models.IntegerField(default=0)),
                ('media_file', models.ImageField(height_field='height', upload_to='', width_field='width')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': 'image',
                'verbose_name_plural': 'images',
            },
        ),
        migrations.CreateModel(
            name='Thumbnail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('title', models.CharField(blank=True, default='', max_length=128)),
                ('caption', models.CharField(blank=True, default='', max_length=128)),
                ('alt_text', models.CharField(blank=True, default='', max_length=128)),
                ('slug', models.SlugField(blank=True, default='', max_length=64)),
                ('extension', models.CharField(blank=True, default='', max_length=16)),
                ('height', models.IntegerField(default=0)),
                ('width', models.IntegerField(default=0)),
                ('media_file', models.ImageField(height_field='height', upload_to='', width_field='width')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('original', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mediamanager.Image')),
            ],
            options={
                'verbose_name': 'thumbnail',
                'verbose_name_plural': 'thumbnails',
            },
        ),
    ]
