# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 02:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mediamanager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.BooleanField(choices=[(False, 'Save as Draft'), (True, 'Publish to Blog')], default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('published_on', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(default='', max_length=64)),
                ('slug', models.SlugField(default='', max_length=64, unique=True)),
                ('content', models.TextField(blank=True, default='')),
                ('snippet', models.CharField(blank=True, default='', max_length=160)),
                ('responsive_banners', models.BooleanField(choices=[(False, 'Use Default Banner'), (True, 'Use Default and Responsive Banners')], default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('default_banner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_banner', to='mediamanager.Image')),
                ('large_banner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='large_banner', to='mediamanager.Image')),
                ('medium_banner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medium_banner', to='mediamanager.Image')),
                ('small_banner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='small_banner', to='mediamanager.Image')),
            ],
            options={
                'get_latest_by': 'published_on',
            },
        ),
        migrations.CreateModel(
            name='TaggedPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Post')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_taggedpost_items', to='taggit.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='blog.TaggedPost', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
